version: "3.1"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - php-fpm
    ports:
      - $NGINX_PORT:80
    environment: 
      PUBLIC_FOLDER: $CODE_FOLDER/public
      APP_ENV: $APP_ENV
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_ENABLE_APCU: "on"
        DOCKER_PHP_ENABLE_COMPOSER: "on"
        DOCKER_PHP_ENABLE_LDAP: "off"
        DOCKER_PHP_ENABLE_MEMCACHED: "on"
        DOCKER_PHP_ENABLE_MONGODB: "off"
        DOCKER_PHP_ENABLE_MYSQL: "on"
        DOCKER_PHP_ENABLE_POSTGRESQL: "off"
        DOCKER_PHP_ENABLE_REDIS: "on"
        DOCKER_PHP_ENABLE_SYMFONY: "on"
        DOCKER_PHP_ENABLE_XDEBUG: "on"
    depends_on:
      - mysql
    ports:
      - $PHP_PORT:9000
    volumes:
      - ./app:$CODE_FOLDER
  mysql:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
