version: "3.1"

services:
  nginx:
    image: enrikerf/nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 80:80
      - 9009:9009 # xdebug psort
    volumes:
      - ./app:/var/www/app # if you have public web assets 
  php-fpm:
    image: enrikerf/php-fpm-xdebug:latest
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/app
    environment:
      PHP_IDE_CONFIG: serverName=docker.local 
  mysql:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--lower_case_table_names=2",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw